[default]
    author = ""
    institution = ""
    series = ""
    footer = ""
    header = ""
    ending = ""
    lang = "en"

[example]
    institution = "School of Artificial Intelligence"
    author = "ivaquero"
    footer = "Clayton University"
    header = ""
    ending = "Thanks for Your Attention"
    lang = "en"
